qcacmn/hif/src/ath_procfs: Fix build when ATH_PROCFS_DIAG_SUPPORT is disabled
Technically, only hif_main.h is required in this instance, but this convention makes things look neater.

This corrects the following compilation errors:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ath_procfs.c:248:5: error: no previous prototype for function 'athdiag_procfs_init' [-Werror,-Wmissing-prototypes]
int athdiag_procfs_init(void *scn)
    ^

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ath_procfs.c:252:6: error: no previous prototype for function 'athdiag_procfs_remove' [-Werror,-Wmissing-prototypes]
void athdiag_procfs_remove(void) {}
     ^

Change-Id: I405501bc386b87e9eb90a859f48f4d1da38a85e0