iommu/arm-smmu-debug: Always return 0 for non-void dummy functions
This is to silence the following compilation errors:

In file included from ../drivers/iommu/arm-smmu.c:70:
../drivers/iommu/arm-smmu-debug.h:92:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
../drivers/iommu/arm-smmu-debug.h:96:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
../drivers/iommu/arm-smmu-debug.h:101:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
../drivers/iommu/arm-smmu-debug.h:104:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
../drivers/iommu/arm-smmu-debug.h:120:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
../drivers/iommu/arm-smmu-debug.h:123:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
}
^
6 errors generated.
make[3]: *** [../scripts/Makefile.build:307: drivers/iommu/arm-smmu.o] Error 1
make[2]: *** [../scripts/Makefile.build:521: drivers/iommu] Error 2
make[1]: *** [/github/home/Kernel/Makefile:1191: drivers] Error 2
make[1]: *** Waiting for unfinished jobs....

Fixes: 96f26b88982b2 ("drivers: iommu: Remove debug depedencies")
Signed-off-by: Fiqri Ardyansyah <fiqri15072019@gmail.com>